### ISSUE TITLE
Integrate `scipy` version 1.6.0

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1630]
When `scipy` version 1.6.0 was released our unit tests broke. This issue tracks the following:

- investigating what needs to be changed within evalml to integrate scipy 1.6.0 
- fixing evalml unit tests to work with scipy 1.6.0
- uncapping the the scipy version in `core-requirements.txt`

Failed tests here: https://github.com/alteryx/evalml/pull/1628

**Comment by angela97lin** [comment]
Tracing the error down, LogisticRegression classifier's fit fails with `*** AttributeError: 'str' object has no attribute 'decode'`

**Comment by angela97lin** [comment]
Repro:
```
import string
X, y = X_y_multi()
log_classifier = LogisticRegressionClassifier(random_state=0, penalty='l2', C=1.0, n_jobs=1, multi_class='auto', solver='lbfgs')
X = log_classifier.random_state.random((X.shape[0], len(string.printable)))
col_names = ['column_{}'.format(ascii_char) for ascii_char in string.printable]
X = pd.DataFrame(X, columns=col_names)
log_classifier.fit(X, y)

```

**Comment by angela97lin** [comment]
Tried 
```
col_names = ['column_{}'.format(ascii_char) for ascii_char in string.printable]
for name in col_names:
    name.decode("latin1")
```
And got the same error. The combination of this + the stack trace leads me to think that when LogisticRegression classifier fails to converge, it tries to print a warning message, which requires calling .decode("latin1"), which breaks on an already-decoded string.

**Comment by angela97lin** [comment]
@dsherry @chukarsten 

Tried to dig into this a bit more, found that someone posted a similar issue: https://github.com/scikit-optimize/scikit-optimize/issues/981

Not really sure if there's anything we can do on our end to get around this, since we can't prevent LogisticRegression failing to converge. We could catch the error, but that doesn't feel right. Perhaps it's okay to keep disallow scipy==1.6.0 and wait for the next release. Thoughts?

**Comment by angela97lin** [comment]
Wanted to follow up so I dug more into this by seeing if I could repro this with just scikit-learn. I couldn't 😭:

```
from sklearn.linear_model import LogisticRegression
import string
from sklearn.utils import check_random_state
from evalml.utils.gen_utils import (
    _convert_to_woodwork_structure,
    _convert_woodwork_types_wrapper
)

random_state = check_random_state(0)
evalml_params = {'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 
                 'l1_ratio': None, 'max_iter': 100,
                 'multi_class': 'auto', 'n_jobs': 1, 'penalty': 'l2', 'random_state': random_state,
                 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}
log_classifier_sk = LogisticRegression(**evalml_params)
# log_classifier_sk = LogisticRegression(random_state=random_state, penalty='l2', C=1.0, n_jobs=1, multi_class='auto', solver='lbfgs')
X = random_state.random((X.shape[0], len(string.printable)))
col_names = ['column_{}'.format(ascii_char) for ascii_char in string.printable]
X = pd.DataFrame(X, columns=col_names)
X = _convert_to_woodwork_structure(X)
X = _convert_woodwork_types_wrapper(X.to_dataframe())
y = _convert_to_woodwork_structure(y)
y = _convert_woodwork_types_wrapper(y.to_series())
log_classifier_sk.fit(X, y)
```

This works fine... but using EvalML doesn't:
```
from evalml.pipelines import LogisticRegressionClassifier
X, y = X_y_multi()
log_classifier = LogisticRegressionClassifier(random_state=0, penalty='l2', C=1.0, n_jobs=1, 
                                              multi_class='auto', solver='lbfgs')
X = check_random_state(0).random((X.shape[0], len(string.printable)))
col_names = ['column_{}'.format(ascii_char) for ascii_char in string.printable]
X = pd.DataFrame(X, columns=col_names)
log_classifier.fit(X, y)
```

Ugh! I tried debugging but am quite stuck. Could be of interest to note that https://github.com/scikit-learn/scikit-learn/pull/18711 fixes this issue. This mean that upgrading scikit-learn to >0.24.0 could resolve this?

**Comment by angela97lin** [comment]
Update: let's hold off on this for now, and see if updating scikit-learn to >0.24.0 resolves this issue.
